using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;

namespace TestCoreConsoleApp
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var data = StandardComment.GetData();

            foreach (StandardComment comment in data)
            {
                int i = 0, pos;
                string newText = comment.Text;

                while ((pos = newText.IndexOf("#?#")) > 0)
                {
                    newText = newText.Substring(0, pos) + "{" + i++.ToString() + "}" + newText.Substring(pos + "#?#".Length);
                }


                Console.WriteLine($"ValuesNum = {i},\t Text = \"{newText}\"");
            }
        }
    }


    public class StandardComment
    {
        public string Id { get; set; } = null!;
        public string Text { get; set; }


        public StandardComment()
        {
            Text = null!;
        }


        public static IEnumerable<StandardComment> GetData()
        {
            var data = new[]{
                new StandardComment() { Id = "B01", Text = "50% OF LAMINATIONS ROTATED 90°;"},
                new StandardComment() { Id = "B02", Text = "SPECIAL MEASURES TO REDUCE IRON LOSSES(TRA-NOT.V.19.6.75);"},
                new StandardComment() { Id = "B03", Text = "AIRGAP PUNCHING WITH SLOT PUNCHING TOOL" },
                new StandardComment() { Id = "B04", Text = "slotdim. ident. to #?#;"},
                new StandardComment() { Id = "B05", Text = "stator lamination like #?#;"},
                new StandardComment() { Id = "B06", Text = "stator OD finished;"},
                new StandardComment() { Id = "B08", Text = "airgap punching with NHL#?#;"},
                new StandardComment() { Id = "B09", Text = "S1=#?#MM;"},
                new StandardComment() { Id = "B10", Text = "min. end ring ID #?#;"},
                new StandardComment() { Id = "B11", Text = "separating with slot punching tool;"},
                new StandardComment() { Id = "B12", Text = "cooling slots between winding slots;"},
                new StandardComment() { Id = "B13", Text = "cooling slots above winding slots;"},
                new StandardComment() { Id = "B14", Text = "end ring width #?# mm;"},
                new StandardComment() { Id = "B15", Text = "lamination quality #?#;"},
                new StandardComment() { Id = "C01", Text = "*outer slot as cooling slot;"},
                new StandardComment() { Id = "C02", Text = "*) diameter D1;"},
                new StandardComment() { Id = "C03", Text = "with assembly ventings on rotor surface;"},
                new StandardComment() { Id = "C04", Text = "Special measures to reduce iron losses(TRA-NOT.V.19.6.75);"},
                new StandardComment() { Id = "C05", Text = "** for sleeve bearings cooling slots NAT#?#,D1=#?#MM;"},
                new StandardComment() { Id = "C06", Text = "cooling slot acc. TKU 4015, NAT#?#;"},
                new StandardComment() { Id = "C07", Text = "cooling slot acc. TKU 4015, NAT#?#,NAT#?#;"},
                new StandardComment() { Id = "C08", Text = "airgap punching with slot punching tool;"},
                new StandardComment() { Id = "C09", Text = "LFR.-NUTENSCHNEID-WZ.STANZT NICHT AUF;"},
                new StandardComment() { Id = "C11", Text = "NUTZAHNSICH.N.ANG.V.TK/FV;"},
                new StandardComment() { Id = "C12", Text = "EV.NUTEN AUFBOHREN;"},
                new StandardComment() { Id = "C13", Text = "*NLA#?#+NLB#?#+NGA#?#;"},
                new StandardComment() { Id = "C14", Text = "*NLB#?#+NGA#?#;"},
                new StandardComment() { Id = "C15", Text = "*NLA#?#+NLA#?#;"},
                new StandardComment() { Id = "C16", Text = "opened rotor slot, during casting closed, AX=#?#MM;"},
                new StandardComment() { Id = "C17", Text = "*center dimension;"},
                new StandardComment() { Id = "C18", Text = "*)ENTSPR.TMAUET 3108;"},
                new StandardComment() { Id = "C19", Text = "airgap punching + turning rotor;"},
                new StandardComment() { Id = "C20", Text = "WIG-VERSCHW.N.KAEFIGW.;"},
                new StandardComment() { Id = "C21", Text = "AAX:#?#CM2;"},
                new StandardComment() { Id = "C22", Text = "BEILEGBL.NTG#?#,NUTGR.D.#?#MM;"},
                new StandardComment() { Id = "C23", Text = "*NLB#?#+NLV#?#;"},
                new StandardComment() { Id = "C24", Text = "rotor punching as #?#;"},
                new StandardComment() { Id = "C25", Text = "lamination quality #?#;"},
                new StandardComment() { Id = "C26", Text = "lasered end rings #?#MM;"},
                new StandardComment() { Id = "E01", Text = "Speed range: xxx 1/min - yyy 1/min (M = const.), yyy 1/min - zzz 1/min (P = const.)" },
                new StandardComment() { Id = "E02", Text = "Overload xxx% (included in RMS): xxx 1/min - yyy 1/min Imax = xxx A" },
                new StandardComment() { Id = "E03", Text = "Overload xxx% (included in RMS): at any speed Imax = xxx A" },
                new StandardComment() { Id = "E04", Text = "Efficiency without the losses of the external ventilation" },
                new StandardComment() { Id = "E05", Text = "with tolerance" },
                new StandardComment() { Id = "E06", Text = "without tolerance" },
                new StandardComment() { Id = "E07", Text = "Base frequency: xxx V, xxx HZ" },
                new StandardComment() { Id = "E08", Text = "No stalling at xxx% UN" },
                new StandardComment() { Id = "E09", Text = "Allowable run-up time (xxx% / yyy% UN) : xxx s / yyy s" },
                new StandardComment() { Id = "E10", Text = "Locked rotor time (xxx% UN, warm / cold): xxx s / yyy s" },
                new StandardComment() { Id = "E11", Text = "Direction of rotation: Bidirectional" },
                new StandardComment() { Id = "E12", Text = "Direction of rotation: Unidirectional" },
                new StandardComment() { Id = "E13", Text = "Re-acceleration after a voltage interruption of xxx s with xxx% UN possible" },
                new StandardComment() { Id = "E14", Text = "Consecutive starts: xxx further starts are permitted after xxx minutes standstill" },
                new StandardComment() { Id = "E15", Text = "Fouling factor: xxx m2K/kW" },
                new StandardComment() { Id = "E16", Text = "Speed range: xxx 1/min - yyy 1/min (M~n²)" },
                new StandardComment() { Id = "K01", Text = "W.BETRIEBSBED.ANSCHL.-L.N.PTB-PRUEFR.5.1.FESTL.;"},
                new StandardComment() { Id = "K02", Text = "operation at #?#;"},
                new StandardComment() { Id = "K03", Text = "for above ser.no. bidirectional fan (eta=#?#%);"},
                new StandardComment() { Id = "K04", Text = "inner ventilation AS and BS;"},
                new StandardComment() { Id = "K05", Text = "bigger terminal box required;"},
                new StandardComment() { Id = "K06", Text = "inlet cooling temp. #?#grd c;"},
                new StandardComment() { Id = "K07", Text = "integrated fan motor;"},
                new StandardComment() { Id = "K08", Text = "insulated bearing, shaft voltage;"},
                new StandardComment() { Id = "K09", Text = "M MAX=#?# NM;"},
                new StandardComment() { Id = "K10", Text = "N MAX=#?#/MIN;"},
                new StandardComment() { Id = "K11", Text = "*SPG.-UMRUESTB.,VERSANDSCH.N.AUFGABENUNTERL.;"},
                new StandardComment() { Id = "K12", Text = "for above ser. no. #?# ;"},
                new StandardComment() { Id = "K13", Text = "design with watercooled bearing shields;"},
                new StandardComment() { Id = "K14", Text = "basic design with shaft cooling;"},
                new StandardComment() { Id = "K15", Text = "max. coolwater inlet temperature #?#GRD C;"},
                new StandardComment() { Id = "K16", Text = "strengthen connecting leads;"},
                new StandardComment() { Id = "K17", Text = "*SPG.-UMRUESTB.A.#?#;"},
                new StandardComment() { Id = "K18", Text = "LUFTLEITR.U.LUFTLEITW.V.#?#...;"},
                new StandardComment() { Id = "K19", Text = "WICKELRAUM V. #?#;"},
                new StandardComment() { Id = "K20", Text = "sucking nozzle DE #?#MM;"},
                new StandardComment() { Id = "K21", Text = "bracket for air lead.DE#?#MM,NDE#?#MM;"},
                new StandardComment() { Id = "V01", Text = "abrasion-resistant;"},
                new StandardComment() { Id = "V02", Text = "insulation for #?#kV;"},
                new StandardComment() { Id = "V03", Text = "ISOLATIONSST.>660...1100V;"},
                new StandardComment() { Id = "V04", Text = "4 SP.-END.JE SP.-GR.GETR.HERAUSF.,AEUSS.SP.-K.D.#?#-FACHSP.GETR.ISOLIEREN;"},
                new StandardComment() { Id = "V05", Text = "TEILSPULEN GEGENSEITIG ISOLIEREN;"},
                new StandardComment() { Id = "V09", Text = "ISOLATIONSTYP D.HILFS-WICKL.#?#;"},
                new StandardComment() { Id = "V10", Text = "NUTKASTENAUSLADUNG #?#MM;"},
                new StandardComment() { Id = "V11", Text = "strengthened overhang insulation;"},
                new StandardComment() { Id = "V12", Text = "HUELSENAUSL.W.10KV;"},
                new StandardComment() { Id = "V13", Text = "LEITERVERB.NUTSEIT.VERBACKEN;"},
                new StandardComment() { Id = "V14", Text = "VPI(MISCHISOL.);"},
                new StandardComment() { Id = "V15", Text = "Additional VPI;"},
                new StandardComment() { Id = "V16", Text = "LAENGSZWISCHENL.;"},
                new StandardComment() { Id = "V17", Text = "VPI insulation;"},
                new StandardComment() { Id = "V18", Text = "overhang design for #?#kV;"},
                new StandardComment() { Id = "V19", Text = "AGS 0.15MM;"},
                new StandardComment() { Id = "V20", Text = "EINGANGSSPULENK. UMBANDELN;"},
                new StandardComment() { Id = "V21", Text = "design with higher copper filling;"},
                new StandardComment() { Id = "V22", Text = "conductor material e-AL99.5;"},
                new StandardComment() { Id = "V23", Text = "AUSF.F.ERH.SCHALTHAEUFIGK.;"},
                new StandardComment() { Id = "V25", Text = "GERADER FREIER SCHENKEL F MIN. MM;"},
                new StandardComment() { Id = "V27", Text = "contains #?#% extra for connection end;"},
                new StandardComment() { Id = "V28", Text = "EINSCHL.#?#% ZUSCHLAG F. SU-AUSF.;"},
                new StandardComment() { Id = "V30", Text = "*UNTERTEILTE 2-STAB-SCHLEIFENW.;"},
                new StandardComment() { Id = "V31", Text = "**with cutting scrap for coil knuckle;"},
                new StandardComment() { Id = "V32", Text = "WICKELK.M.ENTWAERMUNGSRING;"},
                new StandardComment() { Id = "V34", Text = "+)3-zonal-winding;"},
                new StandardComment() { Id = "V35", Text = "*group of two coils;"},
                new StandardComment() { Id = "V36", Text = "*group of three coils;"},
                new StandardComment() { Id = "V37", Text = "*group of four coils;"},
                new StandardComment() { Id = "V38", Text = "spreading radius;"},
                new StandardComment() { Id = "V39", Text = "W.K.-ABD.(SIR.-T.);"},
                new StandardComment() { Id = "V40", Text = "EINSCHNUER,WIE B.1MJ;"},
                new StandardComment() { Id = "V41", Text = "filler at slot opening;"},
                new StandardComment() { Id = "V42", Text = "filler at bottom of slot;"},
                new StandardComment() { Id = "V43", Text = "filler between upper and lower layer;"},
                new StandardComment() { Id = "V44", Text = "filler between winding systems;"},
                new StandardComment() { Id = "V45", Text = "filler #?#mm at bottom of slot #?#mm between upper and lower layer;"},
                new StandardComment() { Id = "V46", Text = "Slots to be closed with profile wedges;"},
                new StandardComment() { Id = "V47", Text = "O.NUTGR.STR.;"},
                new StandardComment() { Id = "V49", Text = "filler #?#mm at slot opening;"},
                new StandardComment() { Id = "V50", Text = "antigliding strip #?#mm;"},
                new StandardComment() { Id = "V52", Text = "intersection filler#?#mm;"},
                new StandardComment() { Id = "V53", Text = "Filler.#?#mm at slot opening. #?#mm in the middle;"},
                new StandardComment() { Id = "V54", Text = "WET-TEST;"},
                new StandardComment() { Id = "V55", Text = "longer winding overhang;"},
                new StandardComment() { Id = "V56", Text = "overhang insulation #?#mm;"},
                new StandardComment() { Id = "V57", Text = "LUFT.WICKELKOPF;"},
                new StandardComment() { Id = "V58", Text = "*STROMVERDR.ARM;"},
                new StandardComment() { Id = "V59", Text = "1LA8 design;"},
                new StandardComment() { Id = "V60", Text = "*group of five coils;"},
                new StandardComment() { Id = "V61", Text = "HALBLABILE SCHALTUNG;"},
                new StandardComment() { Id = "V62", Text = "LABILE SCHALTUNG;"},
                new StandardComment() { Id = "V63", Text = "special connection;"},
                new StandardComment() { Id = "V64", Text = "KL.SCHALTB.TRAS#?#;"},
                new StandardComment() { Id = "V65", Text = "SCHALTB.F.ZUSAMMENHAENGEND WICKELN;"},
                new StandardComment() { Id = "V66", Text = "Without balancing cables;"},
                new StandardComment() { Id = "V67", Text = "*at#?#V#?#ohm;"},
                new StandardComment() { Id = "V68", Text = "SPG.-UMRUESTBAR,#?# WICKLUNGSEND.;"},
                new StandardComment() { Id = "V69", Text = "reverse Dahlander connection;"},
                new StandardComment() { Id = "V70", Text = "*)auinger winding: 3 serial double coils per line;"},
                new StandardComment() { Id = "V71", Text = "*)Pam winding;"},
                new StandardComment() { Id = "V72", Text = "**1U 1V 1W;"},
                new StandardComment() { Id = "V73", Text = "**1U1 1V1 1W1,1U2 1V2 1W2;"},
                new StandardComment() { Id = "V74", Text = "**2U 2V 2W;"},
                new StandardComment() { Id = "V75", Text = "**2U1 2V1 2W1,2U2 2V2 2W2;"},
                new StandardComment() { Id = "V76", Text = "**3U 3V 3W;"},
                new StandardComment() { Id = "V77", Text = "**1U 1V 1W,2U 2V 2W;"},
                new StandardComment() { Id = "V78", Text = "**1U 1V 1W,2U 2V 2W,U6 V6 W6;"},
                new StandardComment() { Id = "V79", Text = "**1U 1V 1W,U2 V2 W2,2U 2V 2W,U6 V6 W6;"},
                new StandardComment() { Id = "V80", Text = "**1U 1V 1W,3U 3V 3W;"},
                new StandardComment() { Id = "V81", Text = "**2U 2V 2W,4U 4V 4W;"},
                new StandardComment() { Id = "V82", Text = "**3U 3V 3W,4U 4V 4W;"},
                new StandardComment() { Id = "V83", Text = "**3U2U 3V 3W;"},
                new StandardComment() { Id = "V84", Text = "**1U 1V 1W W6,3U2U 2V 2W N.TRAS7118,KL.3U2U F. both windings.;"},
                new StandardComment() { Id = "V85", Text = "**1U1 1U2 1U5,1V1 1V2 1V5,1W1 1W2 1W5;"},
                new StandardComment() { Id = "V86", Text = "**2U1 2U2 2U5,2V1 2V2 2V5,2W1 2W2 2W5;"},
                new StandardComment() { Id = "V87", Text = "**1Z1 1V1 1W1,1U2 1V2 1W2,2U1 2V1 2W1,2U2 2V2 2W2;"},
                new StandardComment() { Id = "V88", Text = "**T1 T10,T2 T11,T3 T12,ZUS.3 VERBINDUNGSSCHLEIFEN M.BEZ.T4 T7,T5 T8,T6 T9 IN KL.KASTEN FUEHREN;"},
                new StandardComment() { Id = "V89", Text = "**T1 T10,T2 T11,T3 T12 ZUS.3 VERB.N.T#?#AS#?#N;"},
                new StandardComment() { Id = "V90", Text = "**KLEMMENBEZ.T1...T#?#;"},
                new StandardComment() { Id = "V91", Text = "**1U1V1W,3U3V3W,U6V6W6;"},
                new StandardComment() { Id = "V92", Text = "SCHALTG.M.9 WICKL.-ENDEN GEM.SCHALTBILD;"},
                new StandardComment() { Id = "V93", Text = "modified special connection;"},
                new StandardComment() { Id = "V94", Text = "*TEILSP.ZUSAMMENH.WICKELN,ZWEITEN TEILSP.SATZ VERTAUSCHT EINTR.;"},
                new StandardComment() { Id = "V95", Text = "4 times parallel special connection;"},
                new StandardComment() { Id = "V96", Text = "6 times parallel special connection;"},
                new StandardComment() { Id = "V97", Text = "3 times parallel special connection;"},
                new StandardComment() { Id = "V98", Text = "connection for parallel converters;"},
                new StandardComment() { Id = "W01", Text = "abrasion-resistant;"},
                new StandardComment() { Id = "W02", Text = "insulation for #?#kV;"},
                new StandardComment() { Id = "W03", Text = "ISOLATIONSST.>660...1100V;"},
                new StandardComment() { Id = "W04", Text = "4 SP.-END.JE SP.-GR.GETR.HERAUSF.,AEUSS.SP.-K.D.#?#-FACHSP.GETR.ISOLIEREN;"},
                new StandardComment() { Id = "W05", Text = "TEILSPULEN GEGENSEITIG ISOLIEREN;"},
                new StandardComment() { Id = "W06", Text = "Main insulation on slot side for #?#kV" },
                new StandardComment() { Id = "W07", Text = "CURRENT DISPLACEMENT OPT.;"},
                new StandardComment() { Id = "W08", Text = "Bundle transposition;"},
                new StandardComment() { Id = "W09", Text = "Insulation type of auxiliary winding#?#;"},
                new StandardComment() { Id = "W10", Text = "NUTKASTENAUSLADUNG #?#MM;"},
                new StandardComment() { Id = "W11", Text = "VERST.SPULENK.-IS.;"},
                new StandardComment() { Id = "W12", Text = "HUELSENAUSL.W.10KV;"},
                new StandardComment() { Id = "W13", Text = "LEITERVERB.NUTSEIT.VERBACKEN;"},
                new StandardComment() { Id = "W14", Text = "VPI(MISCHISOL.);"},
                new StandardComment() { Id = "W15", Text = "Additional VPI" },
                new StandardComment() { Id = "W16", Text = "LAENGSZWISCHENL.;"},
                new StandardComment() { Id = "W17", Text = "VPI-IMPR.;"},
                new StandardComment() { Id = "W18", Text = "Layout of winding overhang relates to#?#kV;"},
                new StandardComment() { Id = "W19", Text = "AGS 0.15MM;"},
                new StandardComment() { Id = "W20", Text = "EINGANGSSPULENK. UMBANDELN;"},
                new StandardComment() { Id = "W21", Text = "design with increased copper filling;"},
                new StandardComment() { Id = "W22", Text = "conductor material e-AL99.5;"},
                new StandardComment() { Id = "W23", Text = "Design for increased starting frequency;"},
                new StandardComment() { Id = "W25", Text = "GERADER FREIER SCHENKEL F MIN.#?#MM;"},
                new StandardComment() { Id = "W27", Text = "*ENTHAELT #?#% ZUSCHLAG F.SCHALTENDEN;"},
                new StandardComment() { Id = "W28", Text = "EINSCHL.#?#% ZUSCHLAG F. SU-AUSF.;"},
                new StandardComment() { Id = "W30", Text = "*UNTERTEILTE 2-STAB-SCHLEIFENW.;"},
                new StandardComment() { Id = "W31", Text = "**M.VERSCHNITT F.SPULENNASEN;"},
                new StandardComment() { Id = "W32", Text = "WICKELK.M.ENTWAERMUNGSRING;"},
                new StandardComment() { Id = "W34", Text = "+)3-zonal-winding;"},
                new StandardComment() { Id = "W35", Text = "*group of two coils;"},
                new StandardComment() { Id = "W36", Text = "*group of three coils;"},
                new StandardComment() { Id = "W37", Text = "*group of four coils;"},
                new StandardComment() { Id = "W38", Text = "spreading radius;"},
                new StandardComment() { Id = "W39", Text = "W.K.-ABD.(SIR.-T.);"},
                new StandardComment() { Id = "W40", Text = "EINSCHNUER,WIE B.1MJ;"},
                new StandardComment() { Id = "W41", Text = "filler at slot opening;"},
                new StandardComment() { Id = "W42", Text = "filler at bottom of slot;"},
                new StandardComment() { Id = "W43", Text = "filler between upper and lower layer;"},
                new StandardComment() { Id = "W44", Text = "filler between winding systems;"},
                new StandardComment() { Id = "W45", Text = "filler #?#mm at bottom of slot #?#mm between upper and lower layer;"},
                new StandardComment() { Id = "W46", Text = "Slots to be closed with profile wedges;"},
                new StandardComment() { Id = "W47", Text = "O.NUTGR.STR.;"},
                new StandardComment() { Id = "W49", Text = "filler #?#mm at slot opening;"},
                new StandardComment() { Id = "W50", Text = "antigliding strip #?#mm;"},
                new StandardComment() { Id = "W52", Text = "intersection filler#?#mm;"},
                new StandardComment() { Id = "W53", Text = "F'STR.#?#MM A. NUTOEFFN. #?#MM ZW.O.-U.U.-SCH.;"},
                new StandardComment() { Id = "W54", Text = "WET-TEST;"},
                new StandardComment() { Id = "W55", Text = "longer winding overhang;"},
                new StandardComment() { Id = "W56", Text = "overhang insulation #?#mm;"},
                new StandardComment() { Id = "W57", Text = "LUFT.WICKELKOPF;"},
                new StandardComment() { Id = "W58", Text = "*STROMVERDR.ARM;"},
                new StandardComment() { Id = "W59", Text = "1LA8 design;"},
                new StandardComment() { Id = "W60", Text = "*group of five coils;"},
                new StandardComment() { Id = "W61", Text = "HALBLABILE SCHALTUNG;"},
                new StandardComment() { Id = "W62", Text = "LABILE SCHALTUNG;"},
                new StandardComment() { Id = "W63", Text = "special connection;"},
                new StandardComment() { Id = "W64", Text = "KL.SCHALTB.TRAS#?#;"},
                new StandardComment() { Id = "W65", Text = "SCHALTB.F.ZUSAMMENHAENGEND WICKELN;"},
                new StandardComment() { Id = "W66", Text = "Without balancing cables;"},
                new StandardComment() { Id = "W67", Text = "*B.#?#V #?# OHM;"},
                new StandardComment() { Id = "W68", Text = "SPG.-UMRUESTBAR,#?# WICKLUNGSEND.;"},
                new StandardComment() { Id = "W69", Text = "UMGEKEHRTE DAHLANDERSCHALTUNG;"},
                new StandardComment() { Id = "W70", Text = "*)auinger winding: 3 serial double coils per line;"},
                new StandardComment() { Id = "W71", Text = "*)Pam winding;"},
                new StandardComment() { Id = "W72", Text = "**1U 1V 1W;"},
                new StandardComment() { Id = "W73", Text = "**1U1 1V1 1W1,1U2 1V2 1W2;"},
                new StandardComment() { Id = "W74", Text = "**2U 2V 2W;"},
                new StandardComment() { Id = "W75", Text = "**2U1 2V1 2W1,2U2 2V2 2W2;"},
                new StandardComment() { Id = "W76", Text = "**3U 3V 3W;"},
                new StandardComment() { Id = "W77", Text = "**1U 1V 1W,2U 2V 2W;"},
                new StandardComment() { Id = "W78", Text = "**1U 1V 1W,2U 2V 2W,U6 V6 W6;"},
                new StandardComment() { Id = "W79", Text = "**1U 1V 1W,U2 V2 W2,2U 2V 2W,U6 V6 W6;"},
                new StandardComment() { Id = "W80", Text = "**1U 1V 1W,3U 3V 3W;"},
                new StandardComment() { Id = "W81", Text = "**2U 2V 2W,4U 4V 4W;"},
                new StandardComment() { Id = "W82", Text = "**3U 3V 3W,4U 4V 4W;"},
                new StandardComment() { Id = "W83", Text = "**3U2U 3V 3W;"},
                new StandardComment() { Id = "W84", Text = "**1U 1V 1W W6,3U2U 2V 2W N.TRAS7118,KL.3U2U F. both windings.;"},
                new StandardComment() { Id = "W85", Text = "**1U1 1U2 1U5,1V1 1V2 1V5,1W1 1W2 1W5;"},
                new StandardComment() { Id = "W86", Text = "**2U1 2U2 2U5,2V1 2V2 2V5,2W1 2W2 2W5;"},
                new StandardComment() { Id = "W87", Text = "**1Z1 1V1 1W1,1U2 1V2 1W2,2U1 2V1 2W1,2U2 2V2 2W2;"},
                new StandardComment() { Id = "W88", Text = "**T1 T10,T2 T11,T3 T12,ZUS.3 VERBINDUNGSSCHLEIFEN M.BEZ.T4 T7,T5 T8,T6 T9 IN KL.KASTEN FUEHREN;"},
                new StandardComment() { Id = "W89", Text = "**T1 T10,T2 T11,T3 T12 ZUS.3 VERB.N.T#?#AS#?#N;"},
                new StandardComment() { Id = "W90", Text = "**KLEMMENBEZ.T1...T#?#;"},
                new StandardComment() { Id = "W91", Text = "**1U1V1W,3U3V3W,U6V6W6;"},
                new StandardComment() { Id = "W92", Text = "SCHALTG.M.9 WICKL.-ENDEN GEM.SCHALTBILD;"},
                new StandardComment() { Id = "W93", Text = "modified special connection;"},
                new StandardComment() { Id = "W94", Text = "8 TIMES PARALLEL SPECIAL CONNECTION;"},
                new StandardComment() { Id = "W95", Text = "4 times parallel special connection;"},
                new StandardComment() { Id = "W96", Text = "6 times parallel special connection;"},
                new StandardComment() { Id = "W97", Text = "3 times parallel special connection;"},
                new StandardComment() { Id = "W98", Text = "connection for parallel converters;"},
                new StandardComment() { Id = "W99", Text = "BLACKHOUSE-TEST;"},
                new StandardComment() { Id = "WA1", Text = "TEST;"},
                new StandardComment() { Id = "X01", Text = "balancing ring non-magnetic;"},
                new StandardComment() { Id = "X02", Text = "outer rotor bars swaged;"},
                new StandardComment() { Id = "X03", Text = "INNENST.BEIDERS.HALBR.,ST-BLECH NUR B.INNENST.;"},
                new StandardComment() { Id = "X04", Text = "rotor bars half round on both sides;"},
                new StandardComment() { Id = "X05", Text = "ROTOR BARS CONTINUOUSLY SWAGED;"},
                new StandardComment() { Id = "X06", Text = "Clearance between short circuit ring and preassure ring#?#mm;"},
                new StandardComment() { Id = "X07", Text = "bar conductivity #?#...#?# SIE.M/MM2;"},
                new StandardComment() { Id = "X08", Text = "CUSN8 KAPPA=7 SIE.M/MM2+-10% TOL.;"},
                new StandardComment() { Id = "X09", Text = "all rotor bars insulated from lamination;"},
                new StandardComment() { Id = "X10", Text = "casting mold like #?#;"},
                new StandardComment() { Id = "X11", Text = "STOSS MITTE NUT SEITLICH;"},
                new StandardComment() { Id = "X12", Text = "rings tight-fitting;"},
                new StandardComment() { Id = "X13", Text = "Different ring dimensions, outer=DE, innen=NDE;"},
                new StandardComment() { Id = "X14", Text = "casting mold upper and lower part like #?#;"},
                new StandardComment() { Id = "X15", Text = "DURCHSTECKLOETUNG;"},
                new StandardComment() { Id = "X16", Text = "*KEINE BEARBEITUNG A.D.STIRNSEITE;"},
                new StandardComment() { Id = "X17", Text = "GEN.ABMESSG.N.TK;"},
                new StandardComment() { Id = "X18", Text = "M.WIDERSTANDSFAHNEN A.AS U.BS;"},
                new StandardComment() { Id = "X19", Text = "rotor test voltage #?# V;"},
                new StandardComment() { Id = "X20", Text = "With fan blades on #?#;"},
                new StandardComment() { Id = "X21", Text = "TRAGR.AMAGNET.;"},
                new StandardComment() { Id = "X22", Text = "rotor bars swaged on total length;"},
                new StandardComment() { Id = "X23", Text = "solder L-AG15P;"},
                new StandardComment() { Id = "X24", Text = "solder L-AG44;"},
                new StandardComment() { Id = "X25", Text = "rotor endplate to be TIG welded;"},
                new StandardComment() { Id = "X26", Text = "filler at bottom of slot;"},
                new StandardComment() { Id = "X27", Text = "ring/wings for <=11kV;"},
                new StandardComment() { Id = "X28", Text = "impregnation with epoxy resin;"},
                new StandardComment() { Id = "X29", Text = "Hight of wedge#?#mm;"},
                new StandardComment() { Id = "X30", Text = "Wings on DE and NDE shortened;"},
                new StandardComment() { Id = "X31", Text = "Rotor winding for n<=3000 1/min;"},
                new StandardComment() { Id = "X32", Text = "*VPI acc. WIV 920.1;"},
            };

            return data;
        }
    }
}
